print("Hello G3!")
print("test with ren")
print("text1")
print("text2")
print("text3")
print("text4")
print("text5")
print("456")
print("text6")

print("test1")
print("test2")
print("test3")
print("test4")
print("test5")
print("test6")